#!/bin/bash

if [ "$1" == "inc" ]; then
	brightnessctl set 10%+
fi

if [ "$1" == "dec" ]; then
	brightnessctl set 10%-
fi

BRIGHTNESS=$(brightnessctl get)
MAX=$(brightnessctl max)
PERCENT=$(echo $((BRIGHTNESS * 100 / MAX)))
MSGTAG="mybrightness"
ICON="indicator-brightness"

dunstify -a "changeBrightness" -u low -i $ICON -h string:x-dunst-stack-tag:$MSGTAG -h int:value:"$PERCENT" "Brightness: ${PERCENT}%"

canberra-gtk-play -i audio-volume-change -d "changeBrightness"
