#!/bin/bash

if [ "$1" == "inc" ]; then
    /usr/bin/brightnessctl --device ite_8291::kbd_backlight set 20%+
fi

if [ "$1" == "dec" ]; then
    /usr/bin/brightnessctl --device ite_8291::kbd_backlight set 20%-
fi

BRIGHTNESS=$(/usr/bin/brightnessctl --device ite_8291::kbd_backlight get)
MAX=$(/usr/bin/brightnessctl --device ite_8291::kbd_backlight max)
PERCENT=$(echo $((BRIGHTNESS*100/MAX)))

NOTI_ID=$(notify-send.py "Keyboard backlight" "$PERCENT%" \
                         --hint string:image-path:video-display boolean:transient:true \
                                int:has-percentage:$PERCENT \
                         --replaces-process "keyboard-brightness-popup")
