#!/bin/bash

if [ "$1" == "inc" ]; then
	pamixer -i 10
fi

if [ "$1" == "dec" ]; then
	pamixer -d 10
fi

if [ "$1" == "mute" ]; then
	pamixer -t
fi

VOLUME=$(pamixer --get-volume)
MUTE=$(pamixer --get-mute)
MSGTAG="myvolume"

echo $VOLUME
echo $MUTE

if [[ $VOLUME -le 20 ]]; then
	echo "LESS THAN 20"
	ICON=audio-volume-low
elif [[ $VOLUME -le 60 ]]; then
	echo "LESS THAN 60"
	ICON=audio-volume-medium
else
	ICON=audio-volume-high
fi
if [ "$MUTE" == "true" ]; then
	ICON=audio-volume-muted
fi

if [[ $VOLUME == 0 || "$MUTE" == "off" ]]; then
	dunstify -a "changeVolume" -u low -i $ICON -h string:x-dunst-stack-tag:$MSGTAG
else
	dunstify -a "changeVolume" -u low -i $ICON -h string:x-dunst-stack-tag:$MSGTAG -h int:value:"$VOLUME" "Volume: ${VOLUME}%"
fi

canberra-gtk-play -i audio-volume-change -d "changeVolume"
