#!/bin/bash
sleep 1
echo "stopping xdg-desktop-portal-hyprland"
systemctl --user stop xdg-desktop-portal-hyprland

echo "stopping xdg-desktop-portal-wlr"
systemctl --user stop xdg-desktop-portal-wlr

echo "stopping xdg-desktop-portal-gnome"
systemctl --user stop xdg-desktop-portal-gnome

echo "stopping xdg-desktop-portal"
systemctl --user stop xdg-desktop-portal

sleep 1

echo "starting xdg-desktop-portal-hyprland"
systemctl --user start xdg-desktop-portal-hyprland

sleep 2
echo "starting xdg-desktop-portal-gtk"
systemctl --user start xdg-desktop-portal-gtk

echo "starting xdg-desktop-portal"
systemctl --user start xdg-desktop-portal
