#!/bin/bash

sleep 2

systemctl --user mask xdg-desktop-portal-gnome
systemctl --user stop xdg-desktop-portal-gnome

echo "xdg-desktop-portal-hyprland"
systemctl --user unmask xdg-desktop-portal-hyprland
systemctl --user start xdg-desktop-portal-hyprland

echo "xdg-desktop-portal-gtk"
systemctl --user start xdg-desktop-portal-gtk

echo "xdg-desktop-portal"
systemctl --user stop xdg-desktop-portal
systemctl --user start xdg-desktop-portal
