#!/bin/bash

start() {

  echo "printing portal"
  echo $XDG_DESKTOP_PORTAL
  sleep 1
  echo "stopping xdg-desktop-portal-hyprland"
  systemctl --user stop xdg-desktop-portal-hyprland
  
  echo "stopping xdg-desktop-portal-wlr"
  systemctl --user stop xdg-desktop-portal-wlr
  
  echo "stopping xdg-desktop-portal-gnome"
  systemctl --user stop xdg-desktop-portal-gnome
  
  echo "stopping xdg-desktop-portal"
  systemctl --user stop xdg-desktop-portal

  sleep 1
  
  if [ "$XDG_DESKTOP_PORTAL" != "Hyprland" ];
  then
	  systemctl --user mask xdg-desktop-portal-hyprland
    exit
  else
	  systemctl --user mask xdg-desktop-portal-gnome

          echo "starting xdg-desktop-portal-hyprland"
          systemctl --user start xdg-desktop-portal-hyprland

          echo "starting xdg-desktop-portal-gtk"
          systemctl --user start xdg-desktop-portal-gtk
  fi
  
  echo "starting xdg-desktop-portal"
  systemctl --user start xdg-desktop-portal
}

stop() {
  sleep 1
  echo "stopping xdg-desktop-portal-hyprland"
  systemctl --user stop xdg-desktop-portal-hyprland
  
  echo "stopping xdg-desktop-portal-wlr"
  systemctl --user stop xdg-desktop-portal-wlr
  
  echo "stopping xdg-desktop-portal-gnome"
  systemctl --user stop xdg-desktop-portal-gnome
  
  echo "stopping xdg-desktop-portal"
  systemctl --user stop xdg-desktop-portal

  echo "unmasking xdg-desktop-portal-gnome"
  systemctl --user unmask xdg-desktop-portal-gnome

  echo "unmasking xdg-desktop-portal-hyprland"
  systemctl --user unmask xdg-desktop-portal-hyprland
}

if [ $# -eq 0 ]
then
	echo "No argument supplied"
fi

if [ "$1" = "start" ];
then
	start
elif [ "$1" = "stop" ];
then
	stop
else
	echo "unknown argument. only 'start' and 'stop' accepted"
fi
