plugins:
  - "scratchpads"
  - "expose"
  - "float"
  - "monitors"

options:
  float:
    offset: 0.01

  scratchpads:
    - term:
        command: "alacritty --class gophrland-alacritty"
        float: true
        floatOpts:
          animation: "fromRight"
          margin: 50
        unfocus: "hide"

    - volume:
        command: "alacritty --class gophrland-alacritty -e pulsemixer"
        float: true
        floatOpts:
          animation: "fromRight"
          margin: 50
        unfocus: "hide"

    - slack:
        command: "slack"
        class: "slack"
        float: false

    - whatsapp-for-linux:
        command: "whatsapp-for-linux"
        class: "whatsapp-for-linux"
        float: false
