require('plugins.setup.eslint')
require('plugins.setup.gotopreview')
require('plugins.setup.noneckpain')
require('plugins.setup.silicon')
require('plugins.setup.winpick')
require('plugins.setup.lsp-colors')
